# Generated by Django 2.1 on 2018-08-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=80)),
                ('bookId', models.CharField(max_length=100)),
                ('bookName', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('Quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=80)),
                ('bookId', models.CharField(max_length=100, unique=True)),
                ('bookName', models.CharField(max_length=50, unique=True)),
                ('product', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('Quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('Quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
